// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ggg_user_server.proto

#include "ggg_user_server.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ggg_user {

inline constexpr UserLoginRsp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserLoginRsp::UserLoginRsp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserLoginRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLoginRspDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLoginRspDefaultTypeInternal() {}
  union {
    UserLoginRsp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLoginRspDefaultTypeInternal _UserLoginRsp_default_instance_;

inline constexpr UserLoginReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserLoginReq::UserLoginReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserLoginReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLoginReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLoginReqDefaultTypeInternal() {}
  union {
    UserLoginReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLoginReqDefaultTypeInternal _UserLoginReq_default_instance_;

inline constexpr UserLogOutRsp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserLogOutRsp::UserLogOutRsp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserLogOutRspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLogOutRspDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLogOutRspDefaultTypeInternal() {}
  union {
    UserLogOutRsp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLogOutRspDefaultTypeInternal _UserLogOutRsp_default_instance_;

inline constexpr UserLogOutReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserLogOutReq::UserLogOutReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserLogOutReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLogOutReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLogOutReqDefaultTypeInternal() {}
  union {
    UserLogOutReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLogOutReqDefaultTypeInternal _UserLogOutReq_default_instance_;
}  // namespace ggg_user
static ::_pb::Metadata file_level_metadata_ggg_5fuser_5fserver_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ggg_5fuser_5fserver_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ggg_5fuser_5fserver_2eproto = nullptr;
const ::uint32_t TableStruct_ggg_5fuser_5fserver_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLoginReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLoginReq, _impl_.uid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLoginRsp, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLoginRsp, _impl_.message_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLogOutReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLogOutReq, _impl_.uid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLogOutRsp, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ggg_user::UserLogOutRsp, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ggg_user::UserLoginReq)},
        {9, -1, -1, sizeof(::ggg_user::UserLoginRsp)},
        {18, -1, -1, sizeof(::ggg_user::UserLogOutReq)},
        {27, -1, -1, sizeof(::ggg_user::UserLogOutRsp)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::ggg_user::_UserLoginReq_default_instance_._instance,
    &::ggg_user::_UserLoginRsp_default_instance_._instance,
    &::ggg_user::_UserLogOutReq_default_instance_._instance,
    &::ggg_user::_UserLogOutRsp_default_instance_._instance,
};
const char descriptor_table_protodef_ggg_5fuser_5fserver_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\025ggg_user_server.proto\022\010ggg_user\"\033\n\014Use"
    "rLoginReq\022\013\n\003uid\030\001 \001(\t\"\037\n\014UserLoginRsp\022\017"
    "\n\007message\030\001 \001(\t\"\034\n\rUserLogOutReq\022\013\n\003uid\030"
    "\001 \001(\t\" \n\rUserLogOutRsp\022\017\n\007message\030\001 \001(\t2"
    "\220\001\n\rGggUserServer\022=\n\tUserLogin\022\026.ggg_use"
    "r.UserLoginReq\032\026.ggg_user.UserLoginRsp\"\000"
    "\022@\n\nUserLogOut\022\027.ggg_user.UserLogOutReq\032"
    "\027.ggg_user.UserLogOutRsp\"\000B-\n\020io.grpc.gg"
    "g.userB\017UserServerProtoP\001\242\002\005GUSERb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_ggg_5fuser_5fserver_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ggg_5fuser_5fserver_2eproto = {
    false,
    false,
    361,
    descriptor_table_protodef_ggg_5fuser_5fserver_2eproto,
    "ggg_user_server.proto",
    &descriptor_table_ggg_5fuser_5fserver_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_ggg_5fuser_5fserver_2eproto::offsets,
    file_level_metadata_ggg_5fuser_5fserver_2eproto,
    file_level_enum_descriptors_ggg_5fuser_5fserver_2eproto,
    file_level_service_descriptors_ggg_5fuser_5fserver_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ggg_5fuser_5fserver_2eproto_getter() {
  return &descriptor_table_ggg_5fuser_5fserver_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ggg_5fuser_5fserver_2eproto(&descriptor_table_ggg_5fuser_5fserver_2eproto);
namespace ggg_user {
// ===================================================================

class UserLoginReq::_Internal {
 public:
};

UserLoginReq::UserLoginReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ggg_user.UserLoginReq)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : uid_(arena, from.uid_),
        _cached_size_{0} {}

UserLoginReq::UserLoginReq(
    ::google::protobuf::Arena* arena,
    const UserLoginReq& from)
    : ::google::protobuf::Message(arena) {
  UserLoginReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ggg_user.UserLoginReq)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uid_(arena),
        _cached_size_{0} {}

inline void UserLoginReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserLoginReq::~UserLoginReq() {
  // @@protoc_insertion_point(destructor:ggg_user.UserLoginReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserLoginReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.uid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserLoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:ggg_user.UserLoginReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserLoginReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> UserLoginReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserLoginReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string uid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserLoginReq, _impl_.uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string uid = 1;
    {PROTOBUF_FIELD_OFFSET(UserLoginReq, _impl_.uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\3\0\0\0\0\0\0"
    "ggg_user.UserLoginReq"
    "uid"
  }},
};

::uint8_t* UserLoginReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ggg_user.UserLoginReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string uid = 1;
  if (!this->_internal_uid().empty()) {
    const std::string& _s = this->_internal_uid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ggg_user.UserLoginReq.uid");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ggg_user.UserLoginReq)
  return target;
}

::size_t UserLoginReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ggg_user.UserLoginReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string uid = 1;
  if (!this->_internal_uid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserLoginReq::_class_data_ = {
    UserLoginReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserLoginReq::GetClassData() const {
  return &_class_data_;
}

void UserLoginReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserLoginReq*>(&to_msg);
  auto& from = static_cast<const UserLoginReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ggg_user.UserLoginReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uid().empty()) {
    _this->_internal_set_uid(from._internal_uid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserLoginReq::CopyFrom(const UserLoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ggg_user.UserLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserLoginReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserLoginReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserLoginReq::InternalSwap(UserLoginReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
}

::google::protobuf::Metadata UserLoginReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ggg_5fuser_5fserver_2eproto_getter, &descriptor_table_ggg_5fuser_5fserver_2eproto_once,
      file_level_metadata_ggg_5fuser_5fserver_2eproto[0]);
}
// ===================================================================

class UserLoginRsp::_Internal {
 public:
};

UserLoginRsp::UserLoginRsp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ggg_user.UserLoginRsp)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

UserLoginRsp::UserLoginRsp(
    ::google::protobuf::Arena* arena,
    const UserLoginRsp& from)
    : ::google::protobuf::Message(arena) {
  UserLoginRsp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ggg_user.UserLoginRsp)
}
inline PROTOBUF_NDEBUG_INLINE UserLoginRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void UserLoginRsp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserLoginRsp::~UserLoginRsp() {
  // @@protoc_insertion_point(destructor:ggg_user.UserLoginRsp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserLoginRsp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserLoginRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:ggg_user.UserLoginRsp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserLoginRsp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 37, 2> UserLoginRsp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserLoginRsp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserLoginRsp, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(UserLoginRsp, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\7\0\0\0\0\0\0"
    "ggg_user.UserLoginRsp"
    "message"
  }},
};

::uint8_t* UserLoginRsp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ggg_user.UserLoginRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ggg_user.UserLoginRsp.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ggg_user.UserLoginRsp)
  return target;
}

::size_t UserLoginRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ggg_user.UserLoginRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserLoginRsp::_class_data_ = {
    UserLoginRsp::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserLoginRsp::GetClassData() const {
  return &_class_data_;
}

void UserLoginRsp::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserLoginRsp*>(&to_msg);
  auto& from = static_cast<const UserLoginRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ggg_user.UserLoginRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserLoginRsp::CopyFrom(const UserLoginRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ggg_user.UserLoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserLoginRsp::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserLoginRsp::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserLoginRsp::InternalSwap(UserLoginRsp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata UserLoginRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ggg_5fuser_5fserver_2eproto_getter, &descriptor_table_ggg_5fuser_5fserver_2eproto_once,
      file_level_metadata_ggg_5fuser_5fserver_2eproto[1]);
}
// ===================================================================

class UserLogOutReq::_Internal {
 public:
};

UserLogOutReq::UserLogOutReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ggg_user.UserLogOutReq)
}
inline PROTOBUF_NDEBUG_INLINE UserLogOutReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : uid_(arena, from.uid_),
        _cached_size_{0} {}

UserLogOutReq::UserLogOutReq(
    ::google::protobuf::Arena* arena,
    const UserLogOutReq& from)
    : ::google::protobuf::Message(arena) {
  UserLogOutReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ggg_user.UserLogOutReq)
}
inline PROTOBUF_NDEBUG_INLINE UserLogOutReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uid_(arena),
        _cached_size_{0} {}

inline void UserLogOutReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserLogOutReq::~UserLogOutReq() {
  // @@protoc_insertion_point(destructor:ggg_user.UserLogOutReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserLogOutReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.uid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserLogOutReq::Clear() {
// @@protoc_insertion_point(message_clear_start:ggg_user.UserLogOutReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserLogOutReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> UserLogOutReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserLogOutReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string uid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserLogOutReq, _impl_.uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string uid = 1;
    {PROTOBUF_FIELD_OFFSET(UserLogOutReq, _impl_.uid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\3\0\0\0\0\0\0"
    "ggg_user.UserLogOutReq"
    "uid"
  }},
};

::uint8_t* UserLogOutReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ggg_user.UserLogOutReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string uid = 1;
  if (!this->_internal_uid().empty()) {
    const std::string& _s = this->_internal_uid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ggg_user.UserLogOutReq.uid");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ggg_user.UserLogOutReq)
  return target;
}

::size_t UserLogOutReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ggg_user.UserLogOutReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string uid = 1;
  if (!this->_internal_uid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_uid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserLogOutReq::_class_data_ = {
    UserLogOutReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserLogOutReq::GetClassData() const {
  return &_class_data_;
}

void UserLogOutReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserLogOutReq*>(&to_msg);
  auto& from = static_cast<const UserLogOutReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ggg_user.UserLogOutReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uid().empty()) {
    _this->_internal_set_uid(from._internal_uid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserLogOutReq::CopyFrom(const UserLogOutReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ggg_user.UserLogOutReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserLogOutReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserLogOutReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserLogOutReq::InternalSwap(UserLogOutReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
}

::google::protobuf::Metadata UserLogOutReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ggg_5fuser_5fserver_2eproto_getter, &descriptor_table_ggg_5fuser_5fserver_2eproto_once,
      file_level_metadata_ggg_5fuser_5fserver_2eproto[2]);
}
// ===================================================================

class UserLogOutRsp::_Internal {
 public:
};

UserLogOutRsp::UserLogOutRsp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ggg_user.UserLogOutRsp)
}
inline PROTOBUF_NDEBUG_INLINE UserLogOutRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

UserLogOutRsp::UserLogOutRsp(
    ::google::protobuf::Arena* arena,
    const UserLogOutRsp& from)
    : ::google::protobuf::Message(arena) {
  UserLogOutRsp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:ggg_user.UserLogOutRsp)
}
inline PROTOBUF_NDEBUG_INLINE UserLogOutRsp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void UserLogOutRsp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserLogOutRsp::~UserLogOutRsp() {
  // @@protoc_insertion_point(destructor:ggg_user.UserLogOutRsp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserLogOutRsp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserLogOutRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:ggg_user.UserLogOutRsp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserLogOutRsp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> UserLogOutRsp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserLogOutRsp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserLogOutRsp, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(UserLogOutRsp, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\7\0\0\0\0\0\0"
    "ggg_user.UserLogOutRsp"
    "message"
  }},
};

::uint8_t* UserLogOutRsp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ggg_user.UserLogOutRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ggg_user.UserLogOutRsp.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ggg_user.UserLogOutRsp)
  return target;
}

::size_t UserLogOutRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ggg_user.UserLogOutRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserLogOutRsp::_class_data_ = {
    UserLogOutRsp::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserLogOutRsp::GetClassData() const {
  return &_class_data_;
}

void UserLogOutRsp::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserLogOutRsp*>(&to_msg);
  auto& from = static_cast<const UserLogOutRsp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ggg_user.UserLogOutRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserLogOutRsp::CopyFrom(const UserLogOutRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ggg_user.UserLogOutRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserLogOutRsp::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserLogOutRsp::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserLogOutRsp::InternalSwap(UserLogOutRsp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata UserLogOutRsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ggg_5fuser_5fserver_2eproto_getter, &descriptor_table_ggg_5fuser_5fserver_2eproto_once,
      file_level_metadata_ggg_5fuser_5fserver_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ggg_user
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
